// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	guardMapEvents         = "events"
	guardMapGuardConfig    = "guard_config"
	guardMapTrackedPids    = "tracked_pids"
	guardProgExecguardExit = "execguard_exit"
	guardProgExecguardFork = "execguard_fork"
	guardProgExecguardSec  = "execguard_sec"
)

// loadGuard returns the embedded CollectionSpec for guard.
func loadGuard() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GuardBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load guard: %w", err)
	}

	return spec, err
}

// loadGuardObjects loads guard and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*guardObjects
//	*guardPrograms
//	*guardMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadGuardObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadGuard()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// guardSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type guardSpecs struct {
	guardProgramSpecs
	guardMapSpecs
	guardVariableSpecs
}

// guardProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type guardProgramSpecs struct {
	ExecguardExit *ebpf.ProgramSpec `ebpf:"execguard_exit"`
	ExecguardFork *ebpf.ProgramSpec `ebpf:"execguard_fork"`
	ExecguardSec  *ebpf.ProgramSpec `ebpf:"execguard_sec"`
}

// guardMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type guardMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	GuardConfig *ebpf.MapSpec `ebpf:"guard_config"`
	TrackedPids *ebpf.MapSpec `ebpf:"tracked_pids"`
}

// guardVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type guardVariableSpecs struct {
}

// guardObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type guardObjects struct {
	guardPrograms
	guardMaps
	guardVariables
}

func (o *guardObjects) Close() error {
	return _GuardClose(
		&o.guardPrograms,
		&o.guardMaps,
	)
}

// guardMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type guardMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	GuardConfig *ebpf.Map `ebpf:"guard_config"`
	TrackedPids *ebpf.Map `ebpf:"tracked_pids"`
}

func (m *guardMaps) Close() error {
	return _GuardClose(
		m.Events,
		m.GuardConfig,
		m.TrackedPids,
	)
}

// guardVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type guardVariables struct {
}

// guardPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type guardPrograms struct {
	ExecguardExit *ebpf.Program `ebpf:"execguard_exit"`
	ExecguardFork *ebpf.Program `ebpf:"execguard_fork"`
	ExecguardSec  *ebpf.Program `ebpf:"execguard_sec"`
}

func (p *guardPrograms) Close() error {
	return _GuardClose(
		p.ExecguardExit,
		p.ExecguardFork,
		p.ExecguardSec,
	)
}

func _GuardClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed guard_bpfel.o
var _GuardBytes []byte
